packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.4.5
  '@tanstack/react-query': ^5.87.0
  '@trpc/client': ^11.7.2
  '@trpc/server': ^11.7.2
  '@trpc/tanstack-react-query': ^11.7.2
  better-auth: ^1.4.5
  dotenv: ^17.2.2

ignoredBuiltDependencies:
  - core-js
